import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import React, { useState } from 'react';
import { getSortedPostsData } from './item/itemlist';
import { type } from 'os';
import Item from '@/pages/components/item';

export async function getStaticProps(){
  const res = await fetch('http://localhost:8000/items');
  const listData = await res.json();
  console.log(listData)
  return{ 
    props:{listData}
  }
}

type List = {
  listData: {
    id: number;
    name: string;
    description: string;
    price: number;
    deleted: boolean;
  }[];
};

export default function Home({ listData }: List) {
  return (
    <>
      <Head>
        <title>商品管理</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>商品一覧</h1>
      </main>
      <ul>
        {listData.map((data) => (
          <li key={data.id}>{data.name}</li>
        ))}
      </ul>
      <Link href="components/register">
        <p>商品登録</p>
      </Link>
      <Link href="components/item">
        <p>商品詳細</p>
      </Link>
    </>
  );
}
